### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by metya** [EvanZhouDev/raycast-bard-ai#1]
Hello!
Thanks for developing it!

But seems it doesn't work in raycast with the carefully copied token.
In any commands, I get `⚠️ Unable to reach Bard at this time.` error.

When if select command Ask AI there is always `No input was provided`, and it seems not convenient, cause I want to ask after I type the command Ask AI.

**Comment by williamlwclwc** [comment]
I had the same issue. It turned out that the input is from the texts you selected(e.g. from the browser or text editor), not the raycast input component. I wonder if there can be an option to allow custom input in the raycast input component as well?
